// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG6V2H72yR0B4KRgv9MJnFJ9Geyk1Eb_M',
    appId: '1:945582727760:web:10a0c6803023ef50d4e755',
    messagingSenderId: '945582727760',
    projectId: 'nerdtech-mobile-app',
    authDomain: 'nerdtech-mobile-app.firebaseapp.com',
    storageBucket: 'nerdtech-mobile-app.firebasestorage.app',
    measurementId: 'G-9Y5WYTKN8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACgXCKo3TeUNe_3pSyTytkoKezsooU0C0',
    appId: '1:945582727760:android:140c3afc689b63f0d4e755',
    messagingSenderId: '945582727760',
    projectId: 'nerdtech-mobile-app',
    storageBucket: 'nerdtech-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG6V2H72yR0B4KRgv9MJnFJ9Geyk1Eb_M',
    appId: '1:945582727760:web:36865dd76608c65ad4e755',
    messagingSenderId: '945582727760',
    projectId: 'nerdtech-mobile-app',
    authDomain: 'nerdtech-mobile-app.firebaseapp.com',
    storageBucket: 'nerdtech-mobile-app.firebasestorage.app',
    measurementId: 'G-2332Z9B61Q',
  );

}